{{- if and (eq .Values.demis.enabled true) (eq .Values.demis.futs.split true) }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: futs-bedoccupancy-allow-access-from-internal
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: futs-bedoccupancy
  action: ALLOW
  rules:
    - from:
        - source:
            principals: [
              "cluster.local/ns/{{ .Release.Namespace }}/sa/pdfgen-service*",
            ]
      to:
        - operation:
            methods: [ "GET" ]
            paths: [ "/CodeSystem", "/ValueSet", "/conceptmap/*", "/utils/*" ]
{{ end -}}
